shellcheck:
  stage: test
  image: registry.gitlab.com/pipeline-components/shellcheck:latest
  before_script:
    - shellcheck --version
  script:
    # anything ending on .sh, should be shell script
    #- |
    #  find . -name .git -type d -prune -o -type f  -name \*.sh -print0 |
    #  xargs -0 -P $(nproc) -r -n1 shellcheck
    # magic, any file with a valid shebang should be scanned aswell
    #- |
    #  find . -name .git -type d -prune -o -type f  -regex '.*/[^.]*$'   -print0 |
    #  xargs -0 -P $(nproc) -r -n1 sh -c 'FILE="$0"; if head -n1 "$FILE" |grep -q "^#\\! \?/.\+\(ba|d|k\)\?sh" ; then shellcheck "$FILE" ; else /bin/true ; fi '
    # we know where to look
    - |
      find datastore/eternus/* tm/eternus/* -print0 |
      xargs -0 -P $(nproc) -r -n1 shellcheck -e SC2102,SC2016
#mytest
