#!/usr/bin/env bash

#exec &> >(tee -a "/tmp/eternus-mkfs.log")
set -u

# for Fujitsu Eternus DX series
# <fhe@deepthink.ag>

#cp: copies/dumps the image to the datastore

#ARGUMENTS: datastore_image_dump image_id
#RETURNS: image_source size
#datastore_image_dump is an XML dump of the driver action encoded in Base 64. 
#image_source is the image source which will be later sent to the transfer manager
