#!/bin/bash

# OpenNebula driver for Fujitsu Eternus DX series
# https://github.com/deepthinkag/OpenNebula-addon-eternus/
# <fhe@deepthink.ag>
# <me@florianheigl.me>

#PHASE: INIT

#rm: removes an image from the datastore
#ARGUMENTS: datastore_image_dump image_id
#datastore_image_dump is an XML dump of the driver action encoded in Base 64.
#image_source is the image source which will be later sent to the transfer manager.

#set -u

[[ $# == 2 ]] || exit 1
DRV_ACTION="${1}"
ID="${2}"
DSID="${2}"

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

DRV_PATH=$(dirname  "$0")
DRV_TASK=$(basename "$0")


# source opennebula tools and eternus scripts
for lib in ${LIB_LOCATION}/sh/scripts_common.sh ${DRV_PATH}/../libfs.sh ${DRV_PATH}/scripts_eternus.sh; do
    bash -eun "$lib" && source "$lib" || { echo "Error: failed to set up driver"; exit 1; }
done

# parse XML Data from DRV_ACTION
get_xpath_info

if [[ $DEBUG = "YES" ]]; then
    echo "$DRV_ACTION" > /var/tmp/one/eternus-"${DRV_TASK}"-"${ID}".params
    exec &> >(tee /var/tmp/one/eternus-"${DRV_TASK}-${ID}.log")
fi

#PHASE: PREP
DST_HOST=$( get_destination_host "$ID" )

#PHASE: RUN
VVOL_NAME="one-${ID}"

VVOL_DELETE=$( eternus_ssh_monitor_and_log "${ARRAY_MGMT_IP}" \
               "delete volume -volume-name "${VVOL_NAME}"" )

#PHASE: POST
#RETURNS: -
